### ISSUE TITLE
Class Doctrine\DBAL\Migrations\OutputWriter not found

### ISSUE THREAD

**Issue by anton-kasperovich** [vipsoft/DoctrineDataFixturesExtension#33]
When i try to run:

```
./bin/behat
```

Got this error:

``` php
PHP Fatal error:  Class 'Doctrine\DBAL\Migrations\OutputWriter' not found in /var/www/vendor/vipsoft/doctrine-data-fixtures-extension/src/VIPSoft/DoctrineDataFixturesExtension/Service/FixtureService.php on line 330
```

``` json
#composer.json

"behat/behat": "2.5.*@stable",
"behat/mink": "1.5.*@stable",
"behat/mink-extension": "1.3.*@stable",
"behat/symfony2-extension": "1.1.*@stable",
"behat/mink-goutte-driver": "1.0.*@stable",
"behat/mink-zombie-driver": "1.1.*@stable",
"behat/mink-selenium2-driver": "1.1.*@stable",
"vipsoft/doctrine-data-fixtures-extension": "2.5.3",
```

``` yml
#behat.yml

extensions:
        VIPSoft\DoctrineDataFixturesExtension\Extension:
            lifetime:    feature
            autoload:    true
            directories: ~
            fixtures:    ~
```

I looked up in repository and i found commit 65acc31542abb05d3ae57b6a981c87b4129cb1b8 where "doctrine/migrations is now optional", but, without "doctrine/migrations" i has error :)
