### ISSUE TITLE
[behat 3.0] Fixtures are not reloaded between features

### ISSUE THREAD

**Issue by tristanbes** [vipsoft/DoctrineDataFixturesExtension#39]
Hi,

It seems that the fixtures aren't reloading from feature to feature testing.
The ID in my database remains the same (if the reloads works, the ID would have been either reseted, or either have changed).

Currently i'm testing it with 2 feature files.

```yaml 
        ....
        VIPSoft\DoctrineDataFixturesExtension\Extension:
            lifetime:    feature
            autoload:    false
            directories:
                - apps/features/Context/Fixtures
            fixtures:    ~
            migrations: ~
```

```
    "behat/behat": "3.0.*@dev",
     ...
    "vipsoft/doctrine-data-fixtures-extension": "3.0.*@dev",
